# Generated by Django 2.2.4 on 2020-02-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='user_image',
            new_name='img_con',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='user_name',
            new_name='img_name',
        ),
    ]
